# Generated by Django 2.0.5 on 2018-08-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
