# Generated by Django 2.0.5 on 2018-08-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20180804_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
    ]
