# Generated by Django 2.1 on 2018-08-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20180804_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=30)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='data_de_nascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nome_completo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='idade',
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.Document'),
        ),
    ]
