# Generated by Django 2.1 on 2018-08-10 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_auto_20180810_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Document'),
        ),
    ]
