# Generated by Django 2.1 on 2018-08-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('photo', models.ImageField(upload_to='fotos_casas')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
